### ISSUE TITLE
Editorial Remarks

### ISSUE THREAD

**Issue by ZandarKoad** [makeyourownneuralnetwork/makeyourownneuralnetwork#10]
Hi Tariq!

I'm enjoying your book!  I just purchased it on Kindle so I assume I have the most up to date version.  I'm about half of the way through, and I'm taking detailed notes on my experience, working through the examples.  I have some editorial ideas for improvements.  Would you like me to submit my findings to you?  I do technical documentation for a living, so it may help by serving as a free, technical, editorial review for future versions of your book.

Best,
-Alexander Doak

**Comment by makeyourownneuralnetwork** [comment]
Hi Alexander .. I'm glad you're enjoying the book!

Yes I would appreciate feedback .. it may help improve updates to this
book, or indeed, my next book.

Amazon is a bit rubbish about pushing out updates so I can send you a PDF
of the very latest version. If you bought it since Feb you'll have the
latest.

Tariq
London UK

**Comment by ZandarKoad** [comment]
Great.  Can you contact me via email?  principalwisdom@gmail.com  No sense in publicizing these suggestions/fixes.  :)

**Comment by makeyourownneuralnetwork** [comment]
will do
