### ISSUE TITLE
my own images

### ISSUE THREAD

**Issue by DJN1** [makeyourownneuralnetwork/makeyourownneuralnetwork#48]
My NN doesn't work on my own images, even when I get it to maximum accuracy(97.33%). 
When I draw my images in GIMP, I start by creating a 28x28 canvas so I dont have to compress it.
Instead of `scipy.misc.imread(image_file_name, flatten=True)`
I have to use `skimage.io.imread(image_file_name, as_grey=True)` because `scipy.misc` is deprecated.
Is there too much noise? Is that the problem?
Order for my own images is:
my_own_3.png
my_own_4.png
my_own_6.png
my_own_7.png
![load_images_new](https://user-images.githubusercontent.com/34351129/38221975-e6ccafd4-36a7-11e8-8a1e-bdc967cd36f8.PNG)
![no_match_new](https://user-images.githubusercontent.com/34351129/38221976-e6e0b29a-36a7-11e8-9d30-7f35addbc123.PNG)

**Comment by makeyourownneuralnetwork** [comment]
Hi @DJN1 

I think it might be useful to look at the data that the skimage image loader creates. The image values should range from just above 0 to just below 1. 

If you look at the notebook here, you can see the values range between 0.01 and 1.
[https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/blob/master/part3_neural_network_mnist_and_own_data.ipynb](https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/blob/master/part3_neural_network_mnist_and_own_data.ipynb)

Your screenshot shows the min and mix image values range from about 1.01 and 1.02...

Also make sure the ink is "1" and the white paper is "0" ... which is the opposite of what many libraries and image formats do because they have white as 1 or rgb 255.

**Comment by DJN1** [comment]
Since you have a lot more experience with Python than I do, do you know if there is a better alternative to read the data from the image and make sure it ranges from 0 to 1?

**Comment by DJN1** [comment]
That fixed it. Thank you soo much and sorry for bothering with such belittling issues.
