### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by camx** [makeyourownneuralnetwork/makeyourownneuralnetwork#5]
I am really impressed with the literary and technical content of your book. Even the style you use for your graphics and equations is inspired - a work of art.

Two issues:
1. Your links to this github are incorrect. 
2. Your code here is all .ipnb json. It might be worthwhile putting the .py code in another branch.

Thanks again for a really wonderful introduction to neural nets.

**Comment by makeyourownneuralnetwork** [comment]
Hi camx

Thanks for taking the time to contact me, I really appreciate it.

Please can you give me an exampe of a broken / incorrect link? The links
from my copy seem to work .. ?!

The code in github is posted as ipython notebooks and not pure python. Most
modern browsers will display the notebooks on github correctly, and you can
download the notebooks to be used with our own computer and a notebook
server like the one from Anaconda recommended in the book.

I did thing about pure python and initially didn't go for it because my aim
was to focus on complete beginners and non-technical people. Removing the
messing about with source code fles, command line shells etc was a
priority. I know from teaching basic python to beginners, using notebooks
avoids all that so learners can get on experimenting with python without
any additional complexity.

I think it is a good idea to have a separate branch - I hope I can get
round to doing that soon .. but feel free to do it yourself and I'll share
the links with my blog and twitter.

Thanks

Tariq Rashid
London UK
