### ISSUE TITLE
scipy.misc.imread was removed from scipy

### ISSUE THREAD

**Issue by eimfach** [makeyourownneuralnetwork/makeyourownneuralnetwork#71]
```
import scipy.misc
img_array = scipy.misc.imread(image_file_name, flatten=True) 
img_data = 255.0 - img_array.reshape(784)
img_data = (img_data / 255.0 * 0.99) + 0.01
```

Page 166

`scipy.misc.imread` was removed from the scipy library. They say one can use `imageio` instead.

So this worked for me:
```
# Convert images into float arrays and reduce the colors to gray tones
img_array = imageio.imread("my-images/IMG_2779.png", as_gray=True)
```

https://imageio.readthedocs.io/en/latest/scipy.html

**Comment by makeyourownneuralnetwork** [comment]
Thanks - that looks good.

The code on GitHub was updated to use imageio a couple of years ago - I should update the book text at the next iteration.

**Comment by SavedByZero** [comment]
I'd like to reopen this because I found this error with the suggested update:
`TypeError: The keyword `as_gray` is no longer supported.Use `mode='F'` for a backward-compatible result, or  `mode='L'` for an integer-valued result.`

What's the *most* current suggestion? As someone who comes from games and mainly C#/Haxe/AS3 experience, python drives me absolutely insane with its aggressive and constant deprecations.
